modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "blockhunters"
version = "${version}"
displayName = "Block Hunters"
authors = "Scarlet_Demens"
description = "${mod_description}"
#logoFile = ""

[[dependencies.blockhunters]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockhunters]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockhunters]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blockhunters]]
modId = "midnightlib"
mandatory = true
versionRange = "[${midnightlib_version},)"
ordering = "AFTER"
side = "BOTH"

[mc-publish]
dependencies=[
    "midnightlib(required)",
    "architectury-api(required)"
]